### ISSUE TITLE
Integration not working with HA 2023.2.0

### ISSUE THREAD

**Issue by iStehle** [schlac/hacs-integration-discovergy#16]
`2023-02-02 10:15:18.690 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up discovergy platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 293, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/discovergy/sensor.py", line 228, in async_setup_entry
    DiscovergySensor(
  File "/config/custom_components/discovergy/sensor.py", line 256, in __init__
    self.precision = precision
AttributeError: can't set attribute 'precision'
2023-02-02 10:15:25.082 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up discovergy platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 293, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/discovergy/sensor.py", line 228, in async_setup_entry
    DiscovergySensor(
  File "/config/custom_components/discovergy/sensor.py", line 256, in __init__
    self.precision = precision
AttributeError: can't set attribute 'precision'
`
After the Update the integration stopped working. This is the error I found

**Comment by DerRemo** [comment]
Hi, i have the same Problem since updating to 2023.02. I tried to update the integration to 0.4.2-beta but that didn't resolve the problem i'm still getting the following error message:

`Logger: homeassistant.components.sensor
Source: custom_components/discovergy/sensor.py:256 
Integration: Sensor (documentation, issues) 
First occurred: 10:26:24 (1 occurrences) 
Last logged: 10:26:24

Error while setting up discovergy platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 293, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/discovergy/sensor.py", line 228, in async_setup_entry
    DiscovergySensor(
  File "/config/custom_components/discovergy/sensor.py", line 256, in __init__
    self.precision = precision
AttributeError: can't set attribute 'precision'
`

**Comment by Cyrelion** [comment]
I'm affected by the same problem :(

**Comment by schlac** [comment]
Hi, thx for reporting. **The quick mitigation is to downgrade back to `v0.3.0-beta`.** That looks like it is working for me.

I will try to have a look on the code this evening.

**Comment by iStehle** [comment]
Same Error with the downgrade

`Logger: homeassistant.components.sensor
Source: custom_components/discovergy/sensor.py:256 
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22)) 
First occurred: 16:11:55 (2 occurrences) 
Last logged: 16:42:11

Error while setting up discovergy platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 293, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/discovergy/sensor.py", line 228, in async_setup_entry
    DiscovergySensor(
  File "/config/custom_components/discovergy/sensor.py", line 256, in __init__
    self.precision = precision
AttributeError: can't set attribute 'precision'`

**Comment by iStehle** [comment]
With the downgrade it works again

**Comment by DerRemo** [comment]
For me it worked too.

**Comment by ironboy1** [comment]
> Hi, thx for reporting. **The quick mitigation is to downgrade back to `v0.3.0-beta`.** That looks like it is working for me.
> 
> I will try to have a look on the code this evening.

How to actually perform the downgrade? I'm facing the same issue since updating to the latest HA release

**Comment by schlac** [comment]
@ironboy1 Go to the HACS page on the sidebar, then click on the three dots on the right on the discovery line and select "Redownload".
There you can select the verion in the dropdown. Then just restart HA like after each HACS update.

**Comment by schlac** [comment]
Looks like Jan was fast resolving this on the man PR already. So I think I can tag a new beta in a minute.

**Comment by schlac** [comment]
`v0.4.3-beta` is working with HA 2023.2.0. At least for me.

**Comment by Cyrelion** [comment]
Thank you. Working great again!
