### ISSUE TITLE
Bug with latest HA

### ISSUE THREAD

**Issue by nosuntoday** [schlac/hacs-integration-discovergy#20]
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: homeassistant.loader
Source: custom_components/discovergy/sensor.py:74 
Integration: Discovergy 
First occurred: 22:48:49 (1 occurrences) 
Last logged: 22:48:49

Unexpected exception importing platform custom_components.discovergy.sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 779, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 796, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/discovergy/sensor.py", line 74, in <module>
    DiscovergySensorEntityDescription(
TypeError: DiscovergySensorEntityDescription.__init__() got an unexpected keyword argument 'native_precision'

**Comment by SirVolkie** [comment]
I can confirm to get the same error message as nosuntoday

**Comment by sebster6** [comment]
Can confirm this error occurs with Home Assistant 2023.3.0.

Version info:
Home Assistant 2023.3.0
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230301.0

**Comment by Cyrelion** [comment]
Quick fix:

open the sensor.py file and change all findings of native_precision to suggested_display_precision this will fix the problem for now

**Comment by nosuntoday** [comment]
I can confirm the hot fix. Thank you Cyrelion!

**Comment by PITT72** [comment]
Can confirm it to. I hadn't read this quick fix, so I just removed it and it worked straight away. Can someone tell me what exactly this entry does? Should I use suggested_display_precision instead of just nothing?

**Comment by schlac** [comment]
Thx for reporting. I will update this in the evening.

**Comment by schlac** [comment]
Should be fixed with https://github.com/schlac/hacs-integration-discovergy/releases/tag/v0.4.4-beta.
Will also tag that as latest release if it is still stable in a few days.
