### ISSUE TITLE
Entities lost after update HASS 01.2024

### ISSUE THREAD

**Issue by wunni1** [schlac/hacs-integration-discovergy#25]
After update HomeAsssistant to 01.2024. My Discovergy Energy-Meters are lost. Reboot und re install the integration doesn’t help. The Meters are available from other websites/ integrations, so it should be a problem with the HASS integration after the update.
![IMG_1701](https://github.com/schlac/hacs-integration-discovergy/assets/73655452/7ca79ad6-2d45-4b4c-bd53-b9d507e3d20b)

**Comment by schlac** [comment]
Hi @wunni1, please try without the HACS version of the integration. https://www.home-assistant.io/blog/2023/07/05/release-20237/ did ship the integration directly along with the main distribution. (I updated and that works.)
The switch should be seamless and should also see the history in the same states.

**Comment by wunni1** [comment]
Thank you, used the integration along with the main distribution and it works

**Comment by Maggi0r** [comment]
Hello i have the same Problem. But i deinstalled the HACS Version and reinstalled the Version of main distributuin. But i have no  Devices and entities. 

`Logger: homeassistant.setup
Source: setup.py:403
First occurred: 15:56:48 (1 occurrences)
Last logged: 15:56:48

Unable to prepare setup for platform 'discovergy.sensor': Platform not found (Exception importing custom_components.discovergy.sensor).`

`Logger: homeassistant.loader
Source: loader.py:842
First occurred: 16:08:03 (1 occurrences)
Last logged: 16:08:03

Unexpected exception importing platform custom_components.discovergy.sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 842, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 859, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/discovergy/sensor.py", line 63, in <module>
    DiscovergySensorEntityDescription(
TypeError: DiscovergySensorEntityDescription.__init__() missing 2 required positional arguments: 'alternative_keys' and 'scale'
`
This is from Logfile.

I have found the Post in HA Github and now its finished and done.

**Comment by schlac** [comment]
@Maggi0r This looks like the old files did still get pulled in. Did you restart HA after removing the HACS component?
