### ISSUE TITLE
Platform not found exception in HA 2024.1.2

### ISSUE THREAD

**Issue by samsmooth** [schlac/hacs-integration-discovergy#26]
Unable to prepare setup for platform 'discovergy.sensor': Platform not found (Exception importing custom_components.discovergy.sensor).

`Unexpected exception importing platform custom_components.discovergy.sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 842, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 859, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/discovergy/sensor.py", line 63, in <module>
    DiscovergySensorEntityDescription(
TypeError: DiscovergySensorEntityDescription.__init__() missing 2 required positional arguments: 'alternative_keys' and 'scale'
`

**Comment by schlac** [comment]
https://www.home-assistant.io/blog/2023/07/05/release-20237/ did ship the integration directly along with the main distribution. (I updated and that works.)
The switch should be seamless and should also see the history in the same states. Try to remove the HACS plugin and add the default integration.

**Comment by samsmooth** [comment]
OK, it works now. Thank you for your support!
