### ISSUE TITLE
Werte nicht verfügbar nach HA Neustart

### ISSUE THREAD

**Issue by samsmooth** [schlac/hacs-integration-discovergy#5]
Ich habe das Problem, dass nach einem Neustart die Werte nicht "gezogen" werden. Wenn ich anschließend die Integration deaktiviere und wieder aktiviere sind die Werte wieder da.

Logfile zeigt folgendes:

```Logger: homeassistant.config_entries
Source: custom_components/discovergy/__init__.py:56
Integration: Discovergy
First occurred: 20:58:13 (1 occurrences)
Last logged: 20:58:13

Error setting up entry Discovergy Energy Meter for discovergy
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 61, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 281, in handle_async_request
    ) = await self._pool.handle_async_request(
  File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 234, in handle_async_request
    response = await connection.handle_async_request(
  File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection.py", line 136, in handle_async_request
    self.socket = await self._open_socket(timeout)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection.py", line 163, in _open_socket
    return await self._backend.open_tcp_stream(
  File "/usr/local/lib/python3.9/site-packages/httpcore/_backends/auto.py", line 44, in open_tcp_stream
    return await self.backend.open_tcp_stream(
  File "/usr/local/lib/python3.9/site-packages/httpcore/_backends/anyio.py", line 154, in open_tcp_stream
    stream = await TLSStream.wrap(
  File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc) from None
httpcore.ConnectTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pydiscovergy/discovergy.py", line 50, in _get
    response = await client.get(API_BASE + path)
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1740, in get
    return await self.request(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1494, in request
    response = await self.send(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1586, in send
    response = await self._send_handling_auth(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1616, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1655, in _send_handling_redirects
    response = await self._send_single_request(request, timeout)
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1699, in _send_single_request
    ) = await transport.handle_async_request(
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 276, in handle_async_request
    (
  File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 78, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/discovergy/__init__.py", line 56, in async_setup_entry
    await hass.data[DOMAIN][entry.entry_id].get_meters()
  File "/usr/local/lib/python3.9/site-packages/pydiscovergy/discovergy.py", line 204, in get_meters
    response = await self._get("/meters")
  File "/usr/local/lib/python3.9/site-packages/pydiscovergy/discovergy.py", line 55, in _get
    raise DiscovergyClientError from exc
pydiscovergy.error.DiscovergyClientError
```

Zudem musste ich die Credentials ändern, da mein altes Password mit einer Raute nicht funktionierte.

**Comment by schlac** [comment]
Das sind beides Teile die in der https://github.com/jpbede/pydiscovergy lib passieren.

Bei dem ersten sieht es mir aber eher so aus als sei das wirklich ein generelles Verbindungsproblem zum Server. Dagegen koennte man ausser immer wieder retry nichts tun.

**Comment by jpbede** [comment]
Das ist in der Tat ein ein Timeout, wie @schlac schon sagte.

Der Fehler sollte eigentlich durch die Integration abgefangen werden, sodass HA von sich aus ein Retry macht.
Ich werde den Fehler in der, hoffentlich bald, offizielle Integration abfangen.

**Comment by jpbede** [comment]
@samsmooth Und wegen deinem Problem mit dem `#` werde ich mir natürlich auch noch ansehen :)

**Comment by jpbede** [comment]
@schlac Schau dir mal https://github.com/home-assistant/core/pull/54280/commits/73f2d1c8a6266880a63429be1f4331cd88bd5a2d an, dort habe ich das gefixed :)

**Comment by schlac** [comment]
Sorry, ich wurde mal eben ein wenig vom Leben ueberrollt, sollte jetzt besser werden.
Ich zieh die updates nun rein.

Danke @jpbede !
